### ISSUE TITLE
plans for another release?

### ISSUE THREAD

**Issue by nicolodavis** [lucasem/polytype-rs#23]
I'm keen to use the ability to drop the nom dependency that was merged in #17 but isn't on crates.io yet.

This library is fairly large when compiled to Webassembly (over 1MB) and any ability to trim it down would be helpful.

Keep up the great work!

**Comment by lucasem** [comment]
@joshrule wanna try your new crates.io privileges to make this available?

**Comment by nicolodavis** [comment]
Another suggestion would be to move all the string parsing into a proc macro (assuming that we're only interested in parsing static strings).  That way the parsing happens at compile time (no runtime overhead) and nom effectively becomes a dev dependency.

**Comment by joshrule** [comment]
My personal use cases tend to require parsing at runtime, so I think adding the feature is probably the next step.

@lucasem - happy to handle this, but it may be a few days due to some major preexisting commitments this weekend.

**Comment by joshrule** [comment]
Okay - this has now been resolved by #24!
