### ISSUE TITLE
Generic (or just dynamic) Type and TypeSchema

### ISSUE THREAD

**Issue by blueridanus** [lucasem/polytype-rs#3]
Currently, `Type` is defined as:
```rust
pub enum Type {
    Constructed(&'static str, Vec<Type>),
    Variable(Variable),
}
```
Since the constructor depends on `&'static str`, this has the restriction that all types must be created at compile time. This is does not allow for most use cases of Hindley-Milner, including the most common "adding a type system to a compiler". Ideally, types could be dynamically created.

 I've yet to check the code, but I guess anything that can be compared could be used for identifiers, like this:
```rust
pub enum Type<T: Eq> {
     Constructed(T, Vec<Type<T>>),
    Variable(Variable),
}  
```

**Comment by blueridanus** [comment]
Very cool library, btw!

**Comment by lucasem** [comment]
Hi @blueridanus, thanks for the feedback! I was also unsatisfied with the limitations of using `&'static str` — using traits as you've shown is a good idea. For full compatibility, the trait bound would need to be `Clone + Eq + Display + FromStr`, which is a lot to ask for. I could relax these requirements with separate `impl` blocks, though.

```rust
pub enum Type<T: Clone + Eq> {
    Constructed(T, Vec<Type<T>>),
    Variable(Variable),
}
...
impl<T: Clone + Eq + FromStr> Type<T> {
    fn parse(&str) -> Result<Self, ParseError> { ... }
}
impl<T: Clone + Eq + Display> Display for Type<T> {
    fn fmt(&self, f: &mut fmt::Formatter) -> Result<(), fmt::Error> { ... }
}
impl<T: Clone + Eq + FromStr> FromStr for Type<T> {
    type Error = ParseError;
    fn from_str(&str) -> Result<Self, Self::Error> { ... }
}
```

I'll play around with this!

**Comment by lucasem** [comment]
Upon further inspection, I think the best path forward is a new trait:

```rust
pub trait Name: Clone + Eq {
    fn arrow() -> Self;

    fn show() -> String { ... }
    fn parse(&str) -> Result<Self, ()> { ... }
}
// we provide some impls
impl Name for &'static str { ... }
impl Name for u32 { ... }
```

**Comment by lucasem** [comment]
@blueridanus the [name-trait](/lucasem/polytype-rs/tree/name-trait) branch has an implementation of this, but it slows the library down by about 10%. I might revisit this later when my other work has stabilized.

**Comment by lucasem** [comment]
I was able to do this in a backwards compatible way! It's in the `4.2.0` release — see the [`Name`](https://docs.rs/polytype/~4.2/polytype/trait.Name.html) trait.
